name: Build Chrome and Firefox Extensions

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    tags:
      - 'v*'  # 當有以 v 開頭的標籤被推送時觸發
  pull_request:
    branches: [ main ]

jobs:
  build-chrome:
    name: Build and Package
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Prepare Extension Files
        run: |
          mkdir -p dist/chrome
          cp chrome/manifest.json dist/chrome/
          cp chrome/background.js dist/chrome/
          cp shared/browser-polyfill.min.js dist/chrome/
          cp shared/content.js dist/chrome/
          cp shared/styles.css dist/chrome/
          cp -r shared/icons dist/chrome/
          
      - name: Create ZIP Archive
        run: |
          cd dist/chrome
          zip -r ../../deepwiki-chrome-extension.zip .
        
      - name: Upload Extension Artifact
        uses: actions/upload-artifact@v4
        with:
          name: deepwiki-chrome-extension
          path: dist/chrome
          if-no-files-found: error  # 如果找不到檔案則報錯

      - name: Upload Chrome ZIP Artifact
        uses: actions/upload-artifact@v4
        with:
          name: deepwiki-chrome-extension-zip
          path: deepwiki-chrome-extension.zip
          if-no-files-found: error
  
  build-firefox:
    name: Build Firefox Extension
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Prepare Extension Files
        run: |
          mkdir -p dist/firefox
          cp firefox/manifest.json dist/firefox/
          cp firefox/background.js dist/firefox/
          cp shared/browser-polyfill.min.js dist/firefox/
          cp shared/content.js dist/firefox/
          cp shared/styles.css dist/firefox/
          cp -r shared/icons dist/firefox/
          
      - name: Create ZIP Archive
        run: |
          cd dist/firefox
          zip -r ../../deepwiki-firefox-extension.zip .
      
      - name: Upload Extension Artifact
        uses: actions/upload-artifact@v4
        with:
          name: deepwiki-firefox-extension
          path: dist/firefox
          if-no-files-found: error  # 如果找不到檔案則報錯

      - name: Upload Firefox ZIP Artifact
        uses: actions/upload-artifact@v4
        with:
          name: deepwiki-firefox-extension-zip
          path: deepwiki-firefox-extension.zip
          if-no-files-found: error

  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [build-chrome, build-firefox]
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download Chrome Extension ZIP
        uses: actions/download-artifact@v4
        with:
          name: deepwiki-chrome-extension-zip
          
      - name: Download Firefox Extension ZIP
        uses: actions/download-artifact@v4
        with:
          name: deepwiki-firefox-extension-zip
      
      - name: Get Version
        id: get_version
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: DeepWiki Extension ${{ steps.get_version.outputs.VERSION }}
          files: |
            deepwiki-chrome-extension.zip
            deepwiki-firefox-extension.zip
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}