name: 'Generate Labels'

on:
  pull_request:
    branches: [ main ]

jobs:
  label:
    name: 'Label PR based on title'
    runs-on: ubuntu-latest
    steps:
      - uses: srvaroa/labeler@v1.4
        env:
          GITHUB_TOKEN: ${{ github.token }}